"""Waylay Query: timeseries queries (v1 protocol): REST Models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

version: 0.6.8

 Execute and store queries on the Waylay timeseries.  Protocol version: v1.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.6.8.20260306"

# import models into model package
from .aggregation import Aggregation
from .aggregation1 import Aggregation1
from .aggregation_by_resource_and_metric_value import (
    AggregationByResourceAndMetricValue,
)
from .aggregation_by_resource_and_metric_value1 import (
    AggregationByResourceAndMetricValue1,
)
from .aggregation_by_resource_or_metric_value import AggregationByResourceOrMetricValue
from .aggregation_by_resource_or_metric_value1 import (
    AggregationByResourceOrMetricValue1,
)
from .aggregations_inner import AggregationsInner
from .aggregations_inner1 import AggregationsInner1
from .aggregration import Aggregration
from .align_at import AlignAt
from .align_shift import AlignShift
from .alignment import Alignment
from .alignment_at import AlignmentAt
from .alignment_backward import AlignmentBackward
from .alignment_boundary import AlignmentBoundary
from .alignment_forward import AlignmentForward
from .alignment_from import AlignmentFrom
from .alignment_grid import AlignmentGrid
from .alignment_grid_interval import AlignmentGridInterval
from .alignment_inferred import AlignmentInferred
from .alignment_shift import AlignmentShift
from .alignment_timezone import AlignmentTimezone
from .alignment_until import AlignmentUntil
from .alignment_wrap import AlignmentWrap
from .cause_exception import CauseException
from .column_data_set import ColumnDataSet
from .column_data_set_data_axis import ColumnDataSetDataAxis
from .column_header import ColumnHeader
from .column_headers_inner import ColumnHeadersInner
from .data import Data
from .data_axis_option import DataAxisOption
from .data_set_attributes import DataSetAttributes
from .data_set_window import DataSetWindow
from .datum import Datum
from .default_aggregation import DefaultAggregation
from .default_aggregation1 import DefaultAggregation1
from .default_interpolation import DefaultInterpolation
from .default_interpolation1 import DefaultInterpolation1
from .default_interpolation1_any_of import DefaultInterpolation1AnyOf
from .default_interpolation_any_of import DefaultInterpolationAnyOf
from .delete_response import DeleteResponse
from .embeddings_value import EmbeddingsValue
from .execute_by_name_aggregation import ExecuteByNameAggregation
from .execute_by_name_aggregation_count import ExecuteByNameAggregationCount
from .execute_by_name_aggregation_count_non_numeric import (
    ExecuteByNameAggregationCountNonNumeric,
)
from .execute_by_name_aggregation_count_numeric import (
    ExecuteByNameAggregationCountNumeric,
)
from .execute_by_name_aggregation_first import ExecuteByNameAggregationFirst
from .execute_by_name_aggregation_last import ExecuteByNameAggregationLast
from .execute_by_name_aggregation_max import ExecuteByNameAggregationMax
from .execute_by_name_aggregation_mean import ExecuteByNameAggregationMean
from .execute_by_name_aggregation_median import ExecuteByNameAggregationMedian
from .execute_by_name_aggregation_min import ExecuteByNameAggregationMin
from .execute_by_name_aggregation_std import ExecuteByNameAggregationStd
from .execute_by_name_aggregation_sum import ExecuteByNameAggregationSum
from .execute_by_name_freq import ExecuteByNameFreq
from .execute_by_name_freq_inferred import ExecuteByNameFreqInferred
from .execute_by_name_from import ExecuteByNameFrom
from .execute_by_name_interpolation_akima import ExecuteByNameInterpolationAkima
from .execute_by_name_interpolation_backfill import ExecuteByNameInterpolationBackfill
from .execute_by_name_interpolation_cubic import ExecuteByNameInterpolationCubic
from .execute_by_name_interpolation_fixed import ExecuteByNameInterpolationFixed
from .execute_by_name_interpolation_from_derivatives import (
    ExecuteByNameInterpolationFromDerivatives,
)
from .execute_by_name_interpolation_linear import ExecuteByNameInterpolationLinear
from .execute_by_name_interpolation_nearest import ExecuteByNameInterpolationNearest
from .execute_by_name_interpolation_pad import ExecuteByNameInterpolationPad
from .execute_by_name_interpolation_pchip import ExecuteByNameInterpolationPchip
from .execute_by_name_interpolation_polynomial import (
    ExecuteByNameInterpolationPolynomial,
)
from .execute_by_name_interpolation_quadratic import ExecuteByNameInterpolationQuadratic
from .execute_by_name_interpolation_slinear import ExecuteByNameInterpolationSlinear
from .execute_by_name_interpolation_spline import ExecuteByNameInterpolationSpline
from .execute_by_name_interpolation_zero import ExecuteByNameInterpolationZero
from .execute_by_name_render_compact import ExecuteByNameRenderCOMPACT
from .execute_by_name_render_compactws import ExecuteByNameRenderCOMPACTWS
from .execute_by_name_render_csv import ExecuteByNameRenderCSV
from .execute_by_name_render_flatdict import ExecuteByNameRenderFLATDICT
from .execute_by_name_render_headercolumn import ExecuteByNameRenderHEADERCOLUMN
from .execute_by_name_render_headerrow import ExecuteByNameRenderHEADERROW
from .execute_by_name_render_hierdict import ExecuteByNameRenderHIERDICT
from .execute_by_name_render_metricflatdict import ExecuteByNameRenderMETRICFLATDICT
from .execute_by_name_render_series import ExecuteByNameRenderSERIES
from .execute_by_name_render_upload import ExecuteByNameRenderUPLOAD
from .execute_by_name_until import ExecuteByNameUntil
from .execute_by_name_window import ExecuteByNameWindow
from .execute_query_queries_v1_data_post_aggregation import (
    ExecuteQueryQueriesV1DataPostAggregation,
)
from .execute_query_queries_v1_data_post_aggregation_count import (
    ExecuteQueryQueriesV1DataPostAggregationCount,
)
from .execute_query_queries_v1_data_post_aggregation_count_non_numeric import (
    ExecuteQueryQueriesV1DataPostAggregationCountNonNumeric,
)
from .execute_query_queries_v1_data_post_aggregation_count_numeric import (
    ExecuteQueryQueriesV1DataPostAggregationCountNumeric,
)
from .execute_query_queries_v1_data_post_aggregation_first import (
    ExecuteQueryQueriesV1DataPostAggregationFirst,
)
from .execute_query_queries_v1_data_post_aggregation_last import (
    ExecuteQueryQueriesV1DataPostAggregationLast,
)
from .execute_query_queries_v1_data_post_aggregation_max import (
    ExecuteQueryQueriesV1DataPostAggregationMax,
)
from .execute_query_queries_v1_data_post_aggregation_mean import (
    ExecuteQueryQueriesV1DataPostAggregationMean,
)
from .execute_query_queries_v1_data_post_aggregation_median import (
    ExecuteQueryQueriesV1DataPostAggregationMedian,
)
from .execute_query_queries_v1_data_post_aggregation_min import (
    ExecuteQueryQueriesV1DataPostAggregationMin,
)
from .execute_query_queries_v1_data_post_aggregation_std import (
    ExecuteQueryQueriesV1DataPostAggregationStd,
)
from .execute_query_queries_v1_data_post_aggregation_sum import (
    ExecuteQueryQueriesV1DataPostAggregationSum,
)
from .execute_query_queries_v1_data_post_freq import ExecuteQueryQueriesV1DataPostFreq
from .execute_query_queries_v1_data_post_freq_inferred import (
    ExecuteQueryQueriesV1DataPostFreqInferred,
)
from .execute_query_queries_v1_data_post_from import ExecuteQueryQueriesV1DataPostFrom
from .execute_query_queries_v1_data_post_interpolation_akima import (
    ExecuteQueryQueriesV1DataPostInterpolationAkima,
)
from .execute_query_queries_v1_data_post_interpolation_backfill import (
    ExecuteQueryQueriesV1DataPostInterpolationBackfill,
)
from .execute_query_queries_v1_data_post_interpolation_cubic import (
    ExecuteQueryQueriesV1DataPostInterpolationCubic,
)
from .execute_query_queries_v1_data_post_interpolation_fixed import (
    ExecuteQueryQueriesV1DataPostInterpolationFixed,
)
from .execute_query_queries_v1_data_post_interpolation_from_derivatives import (
    ExecuteQueryQueriesV1DataPostInterpolationFromDerivatives,
)
from .execute_query_queries_v1_data_post_interpolation_linear import (
    ExecuteQueryQueriesV1DataPostInterpolationLinear,
)
from .execute_query_queries_v1_data_post_interpolation_nearest import (
    ExecuteQueryQueriesV1DataPostInterpolationNearest,
)
from .execute_query_queries_v1_data_post_interpolation_pad import (
    ExecuteQueryQueriesV1DataPostInterpolationPad,
)
from .execute_query_queries_v1_data_post_interpolation_parameter import (
    ExecuteQueryQueriesV1DataPostInterpolationParameter,
)
from .execute_query_queries_v1_data_post_interpolation_pchip import (
    ExecuteQueryQueriesV1DataPostInterpolationPchip,
)
from .execute_query_queries_v1_data_post_interpolation_polynomial import (
    ExecuteQueryQueriesV1DataPostInterpolationPolynomial,
)
from .execute_query_queries_v1_data_post_interpolation_quadratic import (
    ExecuteQueryQueriesV1DataPostInterpolationQuadratic,
)
from .execute_query_queries_v1_data_post_interpolation_slinear import (
    ExecuteQueryQueriesV1DataPostInterpolationSlinear,
)
from .execute_query_queries_v1_data_post_interpolation_spline import (
    ExecuteQueryQueriesV1DataPostInterpolationSpline,
)
from .execute_query_queries_v1_data_post_interpolation_zero import (
    ExecuteQueryQueriesV1DataPostInterpolationZero,
)
from .execute_query_queries_v1_data_post_render_compact import (
    ExecuteQueryQueriesV1DataPostRenderCOMPACT,
)
from .execute_query_queries_v1_data_post_render_compactws import (
    ExecuteQueryQueriesV1DataPostRenderCOMPACTWS,
)
from .execute_query_queries_v1_data_post_render_csv import (
    ExecuteQueryQueriesV1DataPostRenderCSV,
)
from .execute_query_queries_v1_data_post_render_flatdict import (
    ExecuteQueryQueriesV1DataPostRenderFLATDICT,
)
from .execute_query_queries_v1_data_post_render_headercolumn import (
    ExecuteQueryQueriesV1DataPostRenderHEADERCOLUMN,
)
from .execute_query_queries_v1_data_post_render_headerrow import (
    ExecuteQueryQueriesV1DataPostRenderHEADERROW,
)
from .execute_query_queries_v1_data_post_render_hierdict import (
    ExecuteQueryQueriesV1DataPostRenderHIERDICT,
)
from .execute_query_queries_v1_data_post_render_metricflatdict import (
    ExecuteQueryQueriesV1DataPostRenderMETRICFLATDICT,
)
from .execute_query_queries_v1_data_post_render_parameter import (
    ExecuteQueryQueriesV1DataPostRenderParameter,
)
from .execute_query_queries_v1_data_post_render_series import (
    ExecuteQueryQueriesV1DataPostRenderSERIES,
)
from .execute_query_queries_v1_data_post_render_upload import (
    ExecuteQueryQueriesV1DataPostRenderUPLOAD,
)
from .execute_query_queries_v1_data_post_until import ExecuteQueryQueriesV1DataPostUntil
from .execute_query_queries_v1_data_post_window import (
    ExecuteQueryQueriesV1DataPostWindow,
)
from .grouping_interval import GroupingInterval
from .grouping_interval1 import GroupingInterval1
from .hal_link import HALLink
from .hal_link_method import HALLinkMethod
from .hal_link_role import HALLinkRole
from .header_array_option import HeaderArrayOption
from .hierarchical import Hierarchical
from .http_validation_error import HTTPValidationError
from .interpolation_method import InterpolationMethod
from .interpolation_method1 import InterpolationMethod1
from .interpolation_method2 import InterpolationMethod2
from .interpolation_method3 import InterpolationMethod3
from .interpolation_parameter import InterpolationParameter
from .interpolation_spec import InterpolationSpec
from .interpolation_spec1 import InterpolationSpec1
from .interpolation_spec2 import InterpolationSpec2
from .interpolation_spec3 import InterpolationSpec3
from .interpolation_spec_akima import InterpolationSpecAkima
from .interpolation_spec_backfill import InterpolationSpecBackfill
from .interpolation_spec_cubic import InterpolationSpecCubic
from .interpolation_spec_fixed import InterpolationSpecFixed
from .interpolation_spec_from_derivatives import InterpolationSpecFromDerivatives
from .interpolation_spec_linear import InterpolationSpecLinear
from .interpolation_spec_nearest import InterpolationSpecNearest
from .interpolation_spec_pad import InterpolationSpecPad
from .interpolation_spec_pchip import InterpolationSpecPchip
from .interpolation_spec_polynomial import InterpolationSpecPolynomial
from .interpolation_spec_quadratic import InterpolationSpecQuadratic
from .interpolation_spec_slinear import InterpolationSpecSlinear
from .interpolation_spec_spline import InterpolationSpecSpline
from .interpolation_spec_zero import InterpolationSpecZero
from .interpolation_specification import InterpolationSpecification
from .interpolation_specification_any_of import InterpolationSpecificationAnyOf
from .links_value import LinksValue
from .location_inner import LocationInner
from .message import Message
from .message_arguments import MessageArguments
from .message_level import MessageLevel
from .message_properties import MessageProperties
from .object_data import ObjectData
from .object_data_set import ObjectDataSet
from .queries_list_response import QueriesListResponse
from .query_definition import QueryDefinition
from .query_entity_input import QueryEntityInput
from .query_execution_message import QueryExecutionMessage
from .query_execution_message_level import QueryExecutionMessageLevel
from .query_hal_links import QueryHALLinks
from .query_input import QueryInput
from .query_input_akima import QueryInputAkima
from .query_input_backfill import QueryInputBackfill
from .query_input_count import QueryInputCount
from .query_input_count_non_numeric import QueryInputCountNonNumeric
from .query_input_count_numeric import QueryInputCountNumeric
from .query_input_cubic import QueryInputCubic
from .query_input_first import QueryInputFirst
from .query_input_fixed import QueryInputFixed
from .query_input_from_derivatives import QueryInputFromDerivatives
from .query_input_inferred import QueryInputInferred
from .query_input_last import QueryInputLast
from .query_input_linear import QueryInputLinear
from .query_input_max import QueryInputMax
from .query_input_mean import QueryInputMean
from .query_input_median import QueryInputMedian
from .query_input_min import QueryInputMin
from .query_input_nearest import QueryInputNearest
from .query_input_pad import QueryInputPad
from .query_input_pchip import QueryInputPchip
from .query_input_polynomial import QueryInputPolynomial
from .query_input_quadratic import QueryInputQuadratic
from .query_input_slinear import QueryInputSlinear
from .query_input_spline import QueryInputSpline
from .query_input_std import QueryInputStd
from .query_input_sum import QueryInputSum
from .query_input_zero import QueryInputZero
from .query_list_hal_links import QueryListHALLinks
from .query_list_item import QueryListItem
from .query_output import QueryOutput
from .query_output_akima import QueryOutputAkima
from .query_output_backfill import QueryOutputBackfill
from .query_output_count import QueryOutputCount
from .query_output_count_non_numeric import QueryOutputCountNonNumeric
from .query_output_count_numeric import QueryOutputCountNumeric
from .query_output_cubic import QueryOutputCubic
from .query_output_first import QueryOutputFirst
from .query_output_fixed import QueryOutputFixed
from .query_output_from_derivatives import QueryOutputFromDerivatives
from .query_output_inferred import QueryOutputInferred
from .query_output_last import QueryOutputLast
from .query_output_linear import QueryOutputLinear
from .query_output_max import QueryOutputMax
from .query_output_mean import QueryOutputMean
from .query_output_median import QueryOutputMedian
from .query_output_min import QueryOutputMin
from .query_output_nearest import QueryOutputNearest
from .query_output_pad import QueryOutputPad
from .query_output_pchip import QueryOutputPchip
from .query_output_polynomial import QueryOutputPolynomial
from .query_output_quadratic import QueryOutputQuadratic
from .query_output_slinear import QueryOutputSlinear
from .query_output_spline import QueryOutputSpline
from .query_output_std import QueryOutputStd
from .query_output_sum import QueryOutputSum
from .query_output_zero import QueryOutputZero
from .query_response import QueryResponse
from .query_result import QueryResult
from .query_update_input import QueryUpdateInput
from .render import Render
from .render_compact import RenderCOMPACT
from .render_compactws import RenderCOMPACTWS
from .render_csv import RenderCSV
from .render_flatdict import RenderFLATDICT
from .render_headercolumn import RenderHEADERCOLUMN
from .render_headerrow import RenderHEADERROW
from .render_hierdict import RenderHIERDICT
from .render_metricflatdict import RenderMETRICFLATDICT
from .render_mode import RenderMode
from .render_series import RenderSERIES
from .render_upload import RenderUPLOAD
from .response_data_set import ResponseDataSet
from .row_data_set import RowDataSet
from .row_data_set_data_axis import RowDataSetDataAxis
from .row_header import RowHeader
from .row_headers_inner import RowHeadersInner
from .series_data_set import SeriesDataSet
from .series_spec import SeriesSpec
from .series_spec_akima import SeriesSpecAkima
from .series_spec_backfill import SeriesSpecBackfill
from .series_spec_count import SeriesSpecCount
from .series_spec_count_non_numeric import SeriesSpecCountNonNumeric
from .series_spec_count_numeric import SeriesSpecCountNumeric
from .series_spec_cubic import SeriesSpecCubic
from .series_spec_first import SeriesSpecFirst
from .series_spec_fixed import SeriesSpecFixed
from .series_spec_from_derivatives import SeriesSpecFromDerivatives
from .series_spec_last import SeriesSpecLast
from .series_spec_linear import SeriesSpecLinear
from .series_spec_max import SeriesSpecMax
from .series_spec_mean import SeriesSpecMean
from .series_spec_median import SeriesSpecMedian
from .series_spec_min import SeriesSpecMin
from .series_spec_nearest import SeriesSpecNearest
from .series_spec_pad import SeriesSpecPad
from .series_spec_pchip import SeriesSpecPchip
from .series_spec_polynomial import SeriesSpecPolynomial
from .series_spec_quadratic import SeriesSpecQuadratic
from .series_spec_slinear import SeriesSpecSlinear
from .series_spec_spline import SeriesSpecSpline
from .series_spec_std import SeriesSpecStd
from .series_spec_sum import SeriesSpecSum
from .series_spec_zero import SeriesSpecZero
from .time_window_from import TimeWindowFrom
from .time_window_until import TimeWindowUntil
from .validation_error import ValidationError
from .window import Window

__all__ = [
    "__version__",
    "Aggregation",
    "Aggregation1",
    "AggregationByResourceAndMetricValue",
    "AggregationByResourceAndMetricValue1",
    "AggregationByResourceOrMetricValue",
    "AggregationByResourceOrMetricValue1",
    "AggregationsInner",
    "AggregationsInner1",
    "Aggregration",
    "AlignAt",
    "AlignShift",
    "Alignment",
    "AlignmentAt",
    "AlignmentBackward",
    "AlignmentBoundary",
    "AlignmentForward",
    "AlignmentFrom",
    "AlignmentGrid",
    "AlignmentGridInterval",
    "AlignmentInferred",
    "AlignmentShift",
    "AlignmentTimezone",
    "AlignmentUntil",
    "AlignmentWrap",
    "CauseException",
    "ColumnDataSet",
    "ColumnDataSetDataAxis",
    "ColumnHeader",
    "ColumnHeadersInner",
    "Data",
    "DataAxisOption",
    "DataSetAttributes",
    "DataSetWindow",
    "Datum",
    "DefaultAggregation",
    "DefaultAggregation1",
    "DefaultInterpolation",
    "DefaultInterpolation1",
    "DefaultInterpolation1AnyOf",
    "DefaultInterpolationAnyOf",
    "DeleteResponse",
    "EmbeddingsValue",
    "ExecuteByNameAggregation",
    "ExecuteByNameAggregationCount",
    "ExecuteByNameAggregationCountNonNumeric",
    "ExecuteByNameAggregationCountNumeric",
    "ExecuteByNameAggregationFirst",
    "ExecuteByNameAggregationLast",
    "ExecuteByNameAggregationMax",
    "ExecuteByNameAggregationMean",
    "ExecuteByNameAggregationMedian",
    "ExecuteByNameAggregationMin",
    "ExecuteByNameAggregationStd",
    "ExecuteByNameAggregationSum",
    "ExecuteByNameFreq",
    "ExecuteByNameFreqInferred",
    "ExecuteByNameFrom",
    "ExecuteByNameInterpolationAkima",
    "ExecuteByNameInterpolationBackfill",
    "ExecuteByNameInterpolationCubic",
    "ExecuteByNameInterpolationFixed",
    "ExecuteByNameInterpolationFromDerivatives",
    "ExecuteByNameInterpolationLinear",
    "ExecuteByNameInterpolationNearest",
    "ExecuteByNameInterpolationPad",
    "ExecuteByNameInterpolationPchip",
    "ExecuteByNameInterpolationPolynomial",
    "ExecuteByNameInterpolationQuadratic",
    "ExecuteByNameInterpolationSlinear",
    "ExecuteByNameInterpolationSpline",
    "ExecuteByNameInterpolationZero",
    "ExecuteByNameRenderCOMPACT",
    "ExecuteByNameRenderCOMPACTWS",
    "ExecuteByNameRenderCSV",
    "ExecuteByNameRenderFLATDICT",
    "ExecuteByNameRenderHEADERCOLUMN",
    "ExecuteByNameRenderHEADERROW",
    "ExecuteByNameRenderHIERDICT",
    "ExecuteByNameRenderMETRICFLATDICT",
    "ExecuteByNameRenderSERIES",
    "ExecuteByNameRenderUPLOAD",
    "ExecuteByNameUntil",
    "ExecuteByNameWindow",
    "ExecuteQueryQueriesV1DataPostAggregation",
    "ExecuteQueryQueriesV1DataPostAggregationCount",
    "ExecuteQueryQueriesV1DataPostAggregationCountNonNumeric",
    "ExecuteQueryQueriesV1DataPostAggregationCountNumeric",
    "ExecuteQueryQueriesV1DataPostAggregationFirst",
    "ExecuteQueryQueriesV1DataPostAggregationLast",
    "ExecuteQueryQueriesV1DataPostAggregationMax",
    "ExecuteQueryQueriesV1DataPostAggregationMean",
    "ExecuteQueryQueriesV1DataPostAggregationMedian",
    "ExecuteQueryQueriesV1DataPostAggregationMin",
    "ExecuteQueryQueriesV1DataPostAggregationStd",
    "ExecuteQueryQueriesV1DataPostAggregationSum",
    "ExecuteQueryQueriesV1DataPostFreq",
    "ExecuteQueryQueriesV1DataPostFreqInferred",
    "ExecuteQueryQueriesV1DataPostFrom",
    "ExecuteQueryQueriesV1DataPostInterpolationAkima",
    "ExecuteQueryQueriesV1DataPostInterpolationBackfill",
    "ExecuteQueryQueriesV1DataPostInterpolationCubic",
    "ExecuteQueryQueriesV1DataPostInterpolationFixed",
    "ExecuteQueryQueriesV1DataPostInterpolationFromDerivatives",
    "ExecuteQueryQueriesV1DataPostInterpolationLinear",
    "ExecuteQueryQueriesV1DataPostInterpolationNearest",
    "ExecuteQueryQueriesV1DataPostInterpolationPad",
    "ExecuteQueryQueriesV1DataPostInterpolationParameter",
    "ExecuteQueryQueriesV1DataPostInterpolationPchip",
    "ExecuteQueryQueriesV1DataPostInterpolationPolynomial",
    "ExecuteQueryQueriesV1DataPostInterpolationQuadratic",
    "ExecuteQueryQueriesV1DataPostInterpolationSlinear",
    "ExecuteQueryQueriesV1DataPostInterpolationSpline",
    "ExecuteQueryQueriesV1DataPostInterpolationZero",
    "ExecuteQueryQueriesV1DataPostRenderCOMPACT",
    "ExecuteQueryQueriesV1DataPostRenderCOMPACTWS",
    "ExecuteQueryQueriesV1DataPostRenderCSV",
    "ExecuteQueryQueriesV1DataPostRenderFLATDICT",
    "ExecuteQueryQueriesV1DataPostRenderHEADERCOLUMN",
    "ExecuteQueryQueriesV1DataPostRenderHEADERROW",
    "ExecuteQueryQueriesV1DataPostRenderHIERDICT",
    "ExecuteQueryQueriesV1DataPostRenderMETRICFLATDICT",
    "ExecuteQueryQueriesV1DataPostRenderParameter",
    "ExecuteQueryQueriesV1DataPostRenderSERIES",
    "ExecuteQueryQueriesV1DataPostRenderUPLOAD",
    "ExecuteQueryQueriesV1DataPostUntil",
    "ExecuteQueryQueriesV1DataPostWindow",
    "GroupingInterval",
    "GroupingInterval1",
    "HALLink",
    "HALLinkMethod",
    "HALLinkRole",
    "HTTPValidationError",
    "HeaderArrayOption",
    "Hierarchical",
    "InterpolationMethod",
    "InterpolationMethod1",
    "InterpolationMethod2",
    "InterpolationMethod3",
    "InterpolationParameter",
    "InterpolationSpec",
    "InterpolationSpec1",
    "InterpolationSpec2",
    "InterpolationSpec3",
    "InterpolationSpecAkima",
    "InterpolationSpecBackfill",
    "InterpolationSpecCubic",
    "InterpolationSpecFixed",
    "InterpolationSpecFromDerivatives",
    "InterpolationSpecLinear",
    "InterpolationSpecNearest",
    "InterpolationSpecPad",
    "InterpolationSpecPchip",
    "InterpolationSpecPolynomial",
    "InterpolationSpecQuadratic",
    "InterpolationSpecSlinear",
    "InterpolationSpecSpline",
    "InterpolationSpecZero",
    "InterpolationSpecification",
    "InterpolationSpecificationAnyOf",
    "LinksValue",
    "LocationInner",
    "Message",
    "MessageArguments",
    "MessageLevel",
    "MessageProperties",
    "ObjectData",
    "ObjectDataSet",
    "QueriesListResponse",
    "QueryDefinition",
    "QueryEntityInput",
    "QueryExecutionMessage",
    "QueryExecutionMessageLevel",
    "QueryHALLinks",
    "QueryInput",
    "QueryInputAkima",
    "QueryInputBackfill",
    "QueryInputCount",
    "QueryInputCountNonNumeric",
    "QueryInputCountNumeric",
    "QueryInputCubic",
    "QueryInputFirst",
    "QueryInputFixed",
    "QueryInputFromDerivatives",
    "QueryInputInferred",
    "QueryInputLast",
    "QueryInputLinear",
    "QueryInputMax",
    "QueryInputMean",
    "QueryInputMedian",
    "QueryInputMin",
    "QueryInputNearest",
    "QueryInputPad",
    "QueryInputPchip",
    "QueryInputPolynomial",
    "QueryInputQuadratic",
    "QueryInputSlinear",
    "QueryInputSpline",
    "QueryInputStd",
    "QueryInputSum",
    "QueryInputZero",
    "QueryListHALLinks",
    "QueryListItem",
    "QueryOutput",
    "QueryOutputAkima",
    "QueryOutputBackfill",
    "QueryOutputCount",
    "QueryOutputCountNonNumeric",
    "QueryOutputCountNumeric",
    "QueryOutputCubic",
    "QueryOutputFirst",
    "QueryOutputFixed",
    "QueryOutputFromDerivatives",
    "QueryOutputInferred",
    "QueryOutputLast",
    "QueryOutputLinear",
    "QueryOutputMax",
    "QueryOutputMean",
    "QueryOutputMedian",
    "QueryOutputMin",
    "QueryOutputNearest",
    "QueryOutputPad",
    "QueryOutputPchip",
    "QueryOutputPolynomial",
    "QueryOutputQuadratic",
    "QueryOutputSlinear",
    "QueryOutputSpline",
    "QueryOutputStd",
    "QueryOutputSum",
    "QueryOutputZero",
    "QueryResponse",
    "QueryResult",
    "QueryUpdateInput",
    "Render",
    "RenderCOMPACT",
    "RenderCOMPACTWS",
    "RenderCSV",
    "RenderFLATDICT",
    "RenderHEADERCOLUMN",
    "RenderHEADERROW",
    "RenderHIERDICT",
    "RenderMETRICFLATDICT",
    "RenderMode",
    "RenderSERIES",
    "RenderUPLOAD",
    "ResponseDataSet",
    "RowDataSet",
    "RowDataSetDataAxis",
    "RowHeader",
    "RowHeadersInner",
    "SeriesDataSet",
    "SeriesSpec",
    "SeriesSpecAkima",
    "SeriesSpecBackfill",
    "SeriesSpecCount",
    "SeriesSpecCountNonNumeric",
    "SeriesSpecCountNumeric",
    "SeriesSpecCubic",
    "SeriesSpecFirst",
    "SeriesSpecFixed",
    "SeriesSpecFromDerivatives",
    "SeriesSpecLast",
    "SeriesSpecLinear",
    "SeriesSpecMax",
    "SeriesSpecMean",
    "SeriesSpecMedian",
    "SeriesSpecMin",
    "SeriesSpecNearest",
    "SeriesSpecPad",
    "SeriesSpecPchip",
    "SeriesSpecPolynomial",
    "SeriesSpecQuadratic",
    "SeriesSpecSlinear",
    "SeriesSpecSpline",
    "SeriesSpecStd",
    "SeriesSpecSum",
    "SeriesSpecZero",
    "TimeWindowFrom",
    "TimeWindowUntil",
    "ValidationError",
    "Window",
]
