# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol): REST Models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

version: 0.5.0

 Execute and store queries on the Waylay timeseries.  Protocol version: v1.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.5.0.20240802"

# import models into model package
from .aggregation_by_resource_and_metric import AggregationByResourceAndMetric
from .aggregation_by_resource_or_metric import AggregationByResourceOrMetric
from .aggregation_method import AggregationMethod
from .aggregation_method_one_of import AggregationMethodOneOf
from .aggregation_method_one_of1 import AggregationMethodOneOf1
from .aggregation_method_one_of2 import AggregationMethodOneOf2
from .aggregation_method_one_of3 import AggregationMethodOneOf3
from .aggregation_method_one_of4 import AggregationMethodOneOf4
from .aggregation_method_one_of5 import AggregationMethodOneOf5
from .aggregation_method_one_of6 import AggregationMethodOneOf6
from .aggregation_method_one_of7 import AggregationMethodOneOf7
from .aggregation_method_one_of8 import AggregationMethodOneOf8
from .aggregations_inner import AggregationsInner
from .align_at import AlignAt
from .align_shift import AlignShift
from .alignment import Alignment
from .alignment_grid_interval import AlignmentGridInterval
from .alignment_timezone import AlignmentTimezone
from .cause_exception import CauseException
from .column_data_set import ColumnDataSet
from .column_data_set_data_axis import ColumnDataSetDataAxis
from .column_header import ColumnHeader
from .column_headers_inner import ColumnHeadersInner
from .data_axis_option import DataAxisOption
from .data_set_attributes import DataSetAttributes
from .data_set_window import DataSetWindow
from .datum import Datum
from .default_aggregation import DefaultAggregation
from .default_interpolation import DefaultInterpolation
from .delete_response import DeleteResponse
from .embeddings import Embeddings
from .from_override import FromOverride
from .grouping_interval import GroupingInterval
from .grouping_interval_override import GroupingIntervalOverride
from .grouping_interval_override_one_of import GroupingIntervalOverrideOneOf
from .hal_link import HALLink
from .hal_link_method import HALLinkMethod
from .hal_link_role import HALLinkRole
from .header_array_option import HeaderArrayOption
from .hierarchical import Hierarchical
from .http_validation_error import HTTPValidationError
from .interpolation import Interpolation
from .interpolation_method import InterpolationMethod
from .interpolation_method_one_of import InterpolationMethodOneOf
from .interpolation_method_one_of1 import InterpolationMethodOneOf1
from .interpolation_method_one_of2 import InterpolationMethodOneOf2
from .interpolation_method_one_of3 import InterpolationMethodOneOf3
from .interpolation_method_one_of4 import InterpolationMethodOneOf4
from .interpolation_method_one_of5 import InterpolationMethodOneOf5
from .interpolation_method_one_of6 import InterpolationMethodOneOf6
from .interpolation_method_one_of7 import InterpolationMethodOneOf7
from .interpolation_method_one_of8 import InterpolationMethodOneOf8
from .interpolation_method_one_of9 import InterpolationMethodOneOf9
from .interpolation_method_one_of10 import InterpolationMethodOneOf10
from .interpolation_method_one_of11 import InterpolationMethodOneOf11
from .interpolation_method_one_of12 import InterpolationMethodOneOf12
from .interpolation_method_one_of13 import InterpolationMethodOneOf13
from .interpolation_spec import InterpolationSpec
from .links import Links
from .location_inner import LocationInner
from .message import Message
from .message_arguments import MessageArguments
from .message_level import MessageLevel
from .message_properties import MessageProperties
from .object_data import ObjectData
from .object_data_set import ObjectDataSet
from .object_data_value import ObjectDataValue
from .queries_list_response import QueriesListResponse
from .query_definition import QueryDefinition
from .query_entity_input import QueryEntityInput
from .query_execution_message import QueryExecutionMessage
from .query_execution_message_level import QueryExecutionMessageLevel
from .query_hal_links import QueryHALLinks
from .query_input import QueryInput
from .query_list_hal_links import QueryListHALLinks
from .query_list_item import QueryListItem
from .query_output import QueryOutput
from .query_response import QueryResponse
from .query_result import QueryResult
from .query_update_input import QueryUpdateInput
from .render import Render
from .render1 import Render1
from .render_mode import RenderMode
from .render_mode_one_of import RenderModeOneOf
from .render_mode_one_of1 import RenderModeOneOf1
from .render_mode_one_of2 import RenderModeOneOf2
from .render_mode_one_of3 import RenderModeOneOf3
from .render_mode_one_of4 import RenderModeOneOf4
from .render_mode_one_of5 import RenderModeOneOf5
from .render_mode_one_of6 import RenderModeOneOf6
from .render_mode_one_of7 import RenderModeOneOf7
from .render_mode_one_of8 import RenderModeOneOf8
from .render_mode_one_of9 import RenderModeOneOf9
from .response_data_set import ResponseDataSet
from .row_data_set import RowDataSet
from .row_data_set_data_axis import RowDataSetDataAxis
from .row_header import RowHeader
from .row_headers_inner import RowHeadersInner
from .series_data_set import SeriesDataSet
from .series_spec import SeriesSpec
from .time_window_from import TimeWindowFrom
from .time_window_until import TimeWindowUntil
from .validation_error import ValidationError
from .window import Window
from .window_override import WindowOverride

__all__ = [
    "__version__",
    "AggregationByResourceAndMetric",
    "AggregationByResourceOrMetric",
    "AggregationMethod",
    "AggregationMethodOneOf",
    "AggregationMethodOneOf1",
    "AggregationMethodOneOf2",
    "AggregationMethodOneOf3",
    "AggregationMethodOneOf4",
    "AggregationMethodOneOf5",
    "AggregationMethodOneOf6",
    "AggregationMethodOneOf7",
    "AggregationMethodOneOf8",
    "AggregationsInner",
    "AlignAt",
    "AlignShift",
    "Alignment",
    "AlignmentGridInterval",
    "AlignmentTimezone",
    "CauseException",
    "ColumnDataSet",
    "ColumnDataSetDataAxis",
    "ColumnHeader",
    "ColumnHeadersInner",
    "DataAxisOption",
    "DataSetAttributes",
    "DataSetWindow",
    "Datum",
    "DefaultAggregation",
    "DefaultInterpolation",
    "DeleteResponse",
    "Embeddings",
    "FromOverride",
    "GroupingInterval",
    "GroupingIntervalOverride",
    "GroupingIntervalOverrideOneOf",
    "HALLink",
    "HALLinkMethod",
    "HALLinkRole",
    "HTTPValidationError",
    "HeaderArrayOption",
    "Hierarchical",
    "Interpolation",
    "InterpolationMethod",
    "InterpolationMethodOneOf",
    "InterpolationMethodOneOf1",
    "InterpolationMethodOneOf10",
    "InterpolationMethodOneOf11",
    "InterpolationMethodOneOf12",
    "InterpolationMethodOneOf13",
    "InterpolationMethodOneOf2",
    "InterpolationMethodOneOf3",
    "InterpolationMethodOneOf4",
    "InterpolationMethodOneOf5",
    "InterpolationMethodOneOf6",
    "InterpolationMethodOneOf7",
    "InterpolationMethodOneOf8",
    "InterpolationMethodOneOf9",
    "InterpolationSpec",
    "Links",
    "LocationInner",
    "Message",
    "MessageArguments",
    "MessageLevel",
    "MessageProperties",
    "ObjectData",
    "ObjectDataSet",
    "ObjectDataValue",
    "QueriesListResponse",
    "QueryDefinition",
    "QueryEntityInput",
    "QueryExecutionMessage",
    "QueryExecutionMessageLevel",
    "QueryHALLinks",
    "QueryInput",
    "QueryListHALLinks",
    "QueryListItem",
    "QueryOutput",
    "QueryResponse",
    "QueryResult",
    "QueryUpdateInput",
    "Render",
    "Render1",
    "RenderMode",
    "RenderModeOneOf",
    "RenderModeOneOf1",
    "RenderModeOneOf2",
    "RenderModeOneOf3",
    "RenderModeOneOf4",
    "RenderModeOneOf5",
    "RenderModeOneOf6",
    "RenderModeOneOf7",
    "RenderModeOneOf8",
    "RenderModeOneOf9",
    "ResponseDataSet",
    "RowDataSet",
    "RowDataSetDataAxis",
    "RowHeader",
    "RowHeadersInner",
    "SeriesDataSet",
    "SeriesSpec",
    "TimeWindowFrom",
    "TimeWindowUntil",
    "ValidationError",
    "Window",
    "WindowOverride",
]
