# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import Annotated

from ..models.aggregation_override_one_of import AggregationOverrideOneOf
from ..models.aggregation_override_one_of1 import AggregationOverrideOneOf1
from ..models.aggregation_override_one_of2 import AggregationOverrideOneOf2
from ..models.aggregation_override_one_of3 import AggregationOverrideOneOf3
from ..models.aggregation_override_one_of4 import AggregationOverrideOneOf4
from ..models.aggregation_override_one_of5 import AggregationOverrideOneOf5
from ..models.aggregation_override_one_of6 import AggregationOverrideOneOf6
from ..models.aggregation_override_one_of7 import AggregationOverrideOneOf7
from ..models.aggregation_override_one_of8 import AggregationOverrideOneOf8

AggregationOverride = Union[
    Annotated[AggregationOverrideOneOf, ""],
    Annotated[AggregationOverrideOneOf1, ""],
    Annotated[AggregationOverrideOneOf2, ""],
    Annotated[AggregationOverrideOneOf3, ""],
    Annotated[AggregationOverrideOneOf4, ""],
    Annotated[AggregationOverrideOneOf5, ""],
    Annotated[AggregationOverrideOneOf6, ""],
    Annotated[AggregationOverrideOneOf7, ""],
    Annotated[AggregationOverrideOneOf8, ""],
]
"""AggregationOverride."""
