# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.aggregation_method_one_of import AggregationMethodOneOf
from ..models.aggregation_method_one_of1 import AggregationMethodOneOf1
from ..models.aggregation_method_one_of2 import AggregationMethodOneOf2
from ..models.aggregation_method_one_of3 import AggregationMethodOneOf3
from ..models.aggregation_method_one_of4 import AggregationMethodOneOf4
from ..models.aggregation_method_one_of5 import AggregationMethodOneOf5
from ..models.aggregation_method_one_of6 import AggregationMethodOneOf6
from ..models.aggregation_method_one_of7 import AggregationMethodOneOf7
from ..models.aggregation_method_one_of8 import AggregationMethodOneOf8

AggregationMethod = Union[
    Annotated[AggregationMethodOneOf, ""],
    Annotated[AggregationMethodOneOf1, ""],
    Annotated[AggregationMethodOneOf2, ""],
    Annotated[AggregationMethodOneOf3, ""],
    Annotated[AggregationMethodOneOf4, ""],
    Annotated[AggregationMethodOneOf5, ""],
    Annotated[AggregationMethodOneOf6, ""],
    Annotated[AggregationMethodOneOf7, ""],
    Annotated[AggregationMethodOneOf8, ""],
]
"""AggregationMethod."""
