# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.grouping_interval_override_one_of import GroupingIntervalOverrideOneOf

AlignmentGridInterval = Union[
    Annotated[
        str,
        "A period in [ISO8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) format.",
    ],
    Annotated[GroupingIntervalOverrideOneOf, ""],
]
""" Defines the grid used to align the aggregation window. The window will align at whole-unit multiples of this interval.  For intervals like `PT1D`, that are timezone-dependent, use the  `align.timezone` to fix the absolute timestamp of the grid boundaries.  If not specified, defaults to the `freq` aggregation interval. ."""
