# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.align_at import AlignAt
from ..models.align_shift import AlignShift
from ..models.alignment_grid_interval import AlignmentGridInterval
from ..models.alignment_timezone import AlignmentTimezone


class Alignment(WaylayBaseModel):
    """Aggregation Alignment Options.  Specifies how the aggregation grid is aligned.."""

    at: AlignAt | None = None
    shift: AlignShift | None = None
    freq: AlignmentGridInterval | None = None
    timezone: AlignmentTimezone | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="allow"
    )
