# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import Annotated

AlignmentShift = Union[
    Annotated[
        str,
        "Shift both boundaries (`align.at=grid`) or first boundary (`align.at=until`) backward to align with the grid.",
    ],
    Annotated[
        str,
        "Shift both boundaries (`align.at=grid`) or last boundary (`align.at=from`) forward to align with the grid.",
    ],
    Annotated[
        str,
        "Shift first boundary backward, and last boundary forward to align with the grid",
    ],
]
"""AlignmentShift."""
