# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import Annotated

AlignmentAt = Union[
    Annotated[
        str,
        "Align to a fixed grid defined by the alignment `frequency` and `timezone`.",
    ],
    Annotated[
        str,
        "Align a the `from` boundary if specified, otherwise use the `until` boundary (specfied or computed)",
    ],
    Annotated[str, "Align a the `from` window boundary."],
    Annotated[str, "Align a the `until` window boundary"],
]
"""AlignmentAt."""
