# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.column_header import ColumnHeader

ColumnHeadersInner = Union[
    Annotated[
        str,
        "Header for a column containing a (representation of) the row index value. These headers precede the header attributes for row data.",
    ],
    Annotated[ColumnHeader, ""],
]
"""ColumnHeadersInner."""
