# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.interpolation_method import InterpolationMethod
from ..models.interpolation_spec import InterpolationSpec

DefaultInterpolation = Union[
    Annotated[InterpolationMethod, ""], Annotated[InterpolationSpec, ""]
]
"""Default Interpolation method for the series (if aggregated).."""
