# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Dict, List

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.embeddings import Embeddings
from ..models.links import Links
from ..models.message import Message


class DeleteResponse(WaylayBaseModel):
    """Confirmation of a delete request.."""

    messages: List[Message] | None = None
    links: Dict[str, Links] | None = Field(
        default=None, description="HAL links, indexed by link relation.", alias="_links"
    )
    embeddings: Dict[str, Embeddings] | None = Field(
        default=None,
        description="Hal embeddings, indexed by relation.",
        alias="_embeddings",
    )

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="allow"
    )
