# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Dict,
    List,
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

Embeddings = Union[
    Annotated[Dict[str, object], "Any embedded representation in a HAL response."],
    Annotated[List[Dict[str, object]], ""],
]
"""Embeddings."""
