# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

InterpolationAnyOf = Union[
    Annotated[
        str,
        "Interpolate with the value of the first observed point. This method also extrapolates.",
    ],
    Annotated[
        str,
        "Interpolate with a fixed, user-specified value. This method also extrapolates.",
    ],
    Annotated[
        str,
        "Same as pad, but using the last observed value. This method also extrapolates",
    ],
    Annotated[
        str,
        "Linearly go from the first observed value of the gap to the last observed oneThis method also extrapolates",
    ],
    Annotated[str, "Use the value that is closest in time."],
    Annotated[
        str,
        "Interpolate with a spline function of order 0, which is a piecewise polynomial.",
    ],
    Annotated[
        str,
        "Interpolate with a spline function of order 1, which is a piecewise polynomial.",
    ],
    Annotated[
        str,
        "Interpolate with a spline function of order 2, which is a piecewise polynomial.",
    ],
    Annotated[
        str,
        "Interpolate with a spline function of order 3, which is a piecewise polynomial.",
    ],
    Annotated[
        str,
        "Interpolate with a polynomial of the lowest possible degree passing trough the data points.",
    ],
    Annotated[str, "Interpolate with a spline function of a user-specified order."],
    Annotated[str, "Interpolate with the derivative of order 1."],
    Annotated[str, "Interpolate with a piecewise cubic spline function."],
    Annotated[
        str,
        "Interpolate with a non-smoothing spline of order 2, called Akima interpolation.",
    ],
]
"""InterpolationAnyOf."""
