# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.interpolation_method_one_of import InterpolationMethodOneOf
from ..models.interpolation_method_one_of1 import InterpolationMethodOneOf1
from ..models.interpolation_method_one_of2 import InterpolationMethodOneOf2
from ..models.interpolation_method_one_of3 import InterpolationMethodOneOf3
from ..models.interpolation_method_one_of4 import InterpolationMethodOneOf4
from ..models.interpolation_method_one_of5 import InterpolationMethodOneOf5
from ..models.interpolation_method_one_of6 import InterpolationMethodOneOf6
from ..models.interpolation_method_one_of7 import InterpolationMethodOneOf7
from ..models.interpolation_method_one_of8 import InterpolationMethodOneOf8
from ..models.interpolation_method_one_of9 import InterpolationMethodOneOf9
from ..models.interpolation_method_one_of10 import InterpolationMethodOneOf10
from ..models.interpolation_method_one_of11 import InterpolationMethodOneOf11
from ..models.interpolation_method_one_of12 import InterpolationMethodOneOf12
from ..models.interpolation_method_one_of13 import InterpolationMethodOneOf13

InterpolationMethod = Union[
    Annotated[InterpolationMethodOneOf, ""],
    Annotated[InterpolationMethodOneOf1, ""],
    Annotated[InterpolationMethodOneOf2, ""],
    Annotated[InterpolationMethodOneOf3, ""],
    Annotated[InterpolationMethodOneOf4, ""],
    Annotated[InterpolationMethodOneOf5, ""],
    Annotated[InterpolationMethodOneOf6, ""],
    Annotated[InterpolationMethodOneOf7, ""],
    Annotated[InterpolationMethodOneOf8, ""],
    Annotated[InterpolationMethodOneOf9, ""],
    Annotated[InterpolationMethodOneOf10, ""],
    Annotated[InterpolationMethodOneOf11, ""],
    Annotated[InterpolationMethodOneOf12, ""],
    Annotated[InterpolationMethodOneOf13, ""],
]
"""InterpolationMethod."""
