# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class InterpolationMethodOneOf11(str, Enum):
    """Interpolate with the derivative of order 1.."""

    FROM_DERIVATIVES = "from_derivatives"

    def __str__(self) -> str:
        return str(self.value)
