# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    List,
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.hal_link import HALLink

Links = Union[Annotated[HALLink, ""], Annotated[List[HALLink], ""]]
"""Links."""
