# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.query_input import QueryInput
from ..models.query_update_input import QueryUpdateInput

QueryDefinition = Union[Annotated[QueryUpdateInput, ""], Annotated[QueryInput, ""]]
"""QueryDefinition."""
