# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.render_mode_one_of import RenderModeOneOf
from ..models.render_mode_one_of1 import RenderModeOneOf1
from ..models.render_mode_one_of2 import RenderModeOneOf2
from ..models.render_mode_one_of3 import RenderModeOneOf3
from ..models.render_mode_one_of4 import RenderModeOneOf4
from ..models.render_mode_one_of5 import RenderModeOneOf5
from ..models.render_mode_one_of6 import RenderModeOneOf6
from ..models.render_mode_one_of7 import RenderModeOneOf7
from ..models.render_mode_one_of8 import RenderModeOneOf8
from ..models.render_mode_one_of9 import RenderModeOneOf9

RenderMode = Union[
    Annotated[RenderModeOneOf, ""],
    Annotated[RenderModeOneOf1, ""],
    Annotated[RenderModeOneOf2, ""],
    Annotated[RenderModeOneOf3, ""],
    Annotated[RenderModeOneOf4, ""],
    Annotated[RenderModeOneOf5, ""],
    Annotated[RenderModeOneOf6, ""],
    Annotated[RenderModeOneOf7, ""],
    Annotated[RenderModeOneOf8, ""],
    Annotated[RenderModeOneOf9, ""],
]
"""Render mode configuration keys.."""
