# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) models.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.column_data_set import ColumnDataSet
from ..models.object_data_set import ObjectDataSet
from ..models.row_data_set import RowDataSet
from ..models.series_data_set import SeriesDataSet

ResponseDataSet = Union[
    Annotated[RowDataSet, ""],
    Annotated[SeriesDataSet, ""],
    Annotated[ColumnDataSet, ""],
    Annotated[ObjectDataSet, ""],
]
"""Result timeseries data set, with one time dimension.."""
