# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.aggregration import Aggregration

    AggregrationAdapter = TypeAdapter(Aggregration)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

aggregration_model_schema = json.loads(
    r"""{
  "title" : "Aggregration",
  "type" : "string",
  "description" : "Aggregation method for the series (if aggregated). If missing, the query default is used.",
  "nullable" : true,
  "oneOf" : [ {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_1"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_2"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_3"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_4"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_5"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_6"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_7"
  }, {
    "$ref" : "#/components/schemas/Aggregation_Override__oneOf_8"
  } ]
}
""",
    object_hook=with_example_provider,
)
aggregration_model_schema.update({"definitions": MODEL_DEFINITIONS})

aggregration_faker = JSF(aggregration_model_schema, allow_none_optionals=1)


class AggregrationStub:
    """Aggregration unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return aggregration_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Aggregration":
        """Create Aggregration stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                AggregrationAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return AggregrationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
