# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.aggregation_override_one_of5 import (
        AggregationOverrideOneOf5,
    )

    AggregationOverrideOneOf5Adapter = TypeAdapter(AggregationOverrideOneOf5)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

aggregation_override__one_of_5_model_schema = json.loads(
    r"""{
  "type" : "string",
  "description" : "Use the count of observations in the sample interval.",
  "enum" : [ "count" ]
}
""",
    object_hook=with_example_provider,
)
aggregation_override__one_of_5_model_schema.update({"definitions": MODEL_DEFINITIONS})

aggregation_override__one_of_5_faker = JSF(
    aggregation_override__one_of_5_model_schema, allow_none_optionals=1
)


class AggregationOverrideOneOf5Stub:
    """AggregationOverrideOneOf5 unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return aggregation_override__one_of_5_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "AggregationOverrideOneOf5":
        """Create AggregationOverrideOneOf5 stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                AggregationOverrideOneOf5Adapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return AggregationOverrideOneOf5Adapter.validate_python(
            json, context={"skip_validation": True}
        )
