# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.cause_exception import CauseException

    CauseExceptionAdapter = TypeAdapter(CauseException)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

cause_exception_model_schema = json.loads(
    r"""{
  "required" : [ "message", "stacktrace", "type" ],
  "type" : "object",
  "properties" : {
    "type" : {
      "title" : "Exception Type",
      "type" : "string"
    },
    "message" : {
      "title" : "Exception Message",
      "type" : "string"
    },
    "stacktrace" : {
      "title" : "Stack Trace",
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    }
  },
  "additionalProperties" : true,
  "description" : "Describes the exception that caused a message."
}
""",
    object_hook=with_example_provider,
)
cause_exception_model_schema.update({"definitions": MODEL_DEFINITIONS})

cause_exception_faker = JSF(cause_exception_model_schema, allow_none_optionals=1)


class CauseExceptionStub:
    """CauseException unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return cause_exception_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "CauseException":
        """Create CauseException stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                CauseExceptionAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return CauseExceptionAdapter.validate_python(
            json, context={"skip_validation": True}
        )
