# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.column_headers_inner import ColumnHeadersInner

    ColumnHeadersInnerAdapter = TypeAdapter(ColumnHeadersInner)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

column_headers_inner_model_schema = json.loads(
    r"""{
  "title" : "Column_Headers_inner",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/RowIndexColumnHeader"
  }, {
    "$ref" : "#/components/schemas/ColumnHeader"
  } ]
}
""",
    object_hook=with_example_provider,
)
column_headers_inner_model_schema.update({"definitions": MODEL_DEFINITIONS})

column_headers_inner_faker = JSF(
    column_headers_inner_model_schema, allow_none_optionals=1
)


class ColumnHeadersInnerStub:
    """ColumnHeadersInner unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return column_headers_inner_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "ColumnHeadersInner":
        """Create ColumnHeadersInner stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ColumnHeadersInnerAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ColumnHeadersInnerAdapter.validate_python(
            json, context={"skip_validation": True}
        )
