# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.column_data_set_data_axis import (
        ColumnDataSetDataAxis,
    )

    ColumnDataSetDataAxisAdapter = TypeAdapter(ColumnDataSetDataAxis)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

column_data_set_data_axis_model_schema = json.loads(
    r"""{
  "title" : "ColumnDataSet_data_axis",
  "type" : "string",
  "default" : "row",
  "enum" : [ "row" ]
}
""",
    object_hook=with_example_provider,
)
column_data_set_data_axis_model_schema.update({"definitions": MODEL_DEFINITIONS})

column_data_set_data_axis_faker = JSF(
    column_data_set_data_axis_model_schema, allow_none_optionals=1
)


class ColumnDataSetDataAxisStub:
    """ColumnDataSetDataAxis unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return column_data_set_data_axis_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "ColumnDataSetDataAxis":
        """Create ColumnDataSetDataAxis stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ColumnDataSetDataAxisAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ColumnDataSetDataAxisAdapter.validate_python(
            json, context={"skip_validation": True}
        )
