# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.column_header import ColumnHeader

    ColumnHeaderAdapter = TypeAdapter(ColumnHeader)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

column_header_model_schema = json.loads(
    r"""{
  "required" : [ "metric", "resource" ],
  "type" : "object",
  "properties" : {
    "resource" : {
      "title" : "Series resource id",
      "type" : "string"
    },
    "metric" : {
      "title" : "Series metric",
      "type" : "string"
    },
    "aggregation" : {
      "title" : "Aggregation applied to the series.",
      "type" : "string"
    }
  },
  "additionalProperties" : true,
  "description" : "Column attributes.\n\nAttributes that identify and describe the data in this column."
}
""",
    object_hook=with_example_provider,
)
column_header_model_schema.update({"definitions": MODEL_DEFINITIONS})

column_header_faker = JSF(column_header_model_schema, allow_none_optionals=1)


class ColumnHeaderStub:
    """ColumnHeader unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return column_header_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "ColumnHeader":
        """Create ColumnHeader stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                ColumnHeaderAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ColumnHeaderAdapter.validate_python(
            json, context={"skip_validation": True}
        )
