# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.data import Data

    DataAdapter = TypeAdapter(Data)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

data__model_schema = json.loads(
    r"""{
  "title" : "Data ",
  "oneOf" : [ {
    "title" : "Hierarchical Data",
    "type" : "object",
    "description" : "Values for the series whose attributes corresponds with the key. Keyed by sub-levels."
  }, {
    "$ref" : "#/components/schemas/Datum"
  } ]
}
""",
    object_hook=with_example_provider,
)
data__model_schema.update({"definitions": MODEL_DEFINITIONS})

data__faker = JSF(data__model_schema, allow_none_optionals=1)


class DataStub:
    """Data unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return data__faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Data":
        """Create Data stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(DataAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DataAdapter.validate_python(json, context={"skip_validation": True})
