# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.data_axis_option import DataAxisOption

    DataAxisOptionAdapter = TypeAdapter(DataAxisOption)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

data_axis_option_model_schema = json.loads(
    r"""{
  "type" : "string",
  "description" : "Allowed values for the render.data_axis option.",
  "enum" : [ "row", "column" ]
}
""",
    object_hook=with_example_provider,
)
data_axis_option_model_schema.update({"definitions": MODEL_DEFINITIONS})

data_axis_option_faker = JSF(data_axis_option_model_schema, allow_none_optionals=1)


class DataAxisOptionStub:
    """DataAxisOption unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return data_axis_option_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "DataAxisOption":
        """Create DataAxisOption stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DataAxisOptionAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DataAxisOptionAdapter.validate_python(
            json, context={"skip_validation": True}
        )
