# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.data_set_attributes import DataSetAttributes

    DataSetAttributesAdapter = TypeAdapter(DataSetAttributes)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

data_set_attributes_model_schema = json.loads(
    r"""{
  "title" : "DataSetAttributes",
  "type" : "object",
  "properties" : {
    "role" : {
      "$ref" : "#/components/schemas/Role"
    }
  },
  "additionalProperties" : true,
  "description" : "Data Set Attributes.\n\nData attributes that apply to all data in this set."
}
""",
    object_hook=with_example_provider,
)
data_set_attributes_model_schema.update({"definitions": MODEL_DEFINITIONS})

data_set_attributes_faker = JSF(
    data_set_attributes_model_schema, allow_none_optionals=1
)


class DataSetAttributesStub:
    """DataSetAttributes unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return data_set_attributes_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "DataSetAttributes":
        """Create DataSetAttributes stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DataSetAttributesAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DataSetAttributesAdapter.validate_python(
            json, context={"skip_validation": True}
        )
