# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.default_interpolation import (
        DefaultInterpolation,
    )

    DefaultInterpolationAdapter = TypeAdapter(DefaultInterpolation)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

default_interpolation_model_schema = json.loads(
    r"""{
  "title" : "Default Interpolation",
  "description" : "Default Interpolation method for the series (if aggregated).",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/Interpolation_anyOf"
  }, {
    "$ref" : "#/components/schemas/InterpolationSpec"
  } ]
}
""",
    object_hook=with_example_provider,
)
default_interpolation_model_schema.update({"definitions": MODEL_DEFINITIONS})

default_interpolation_faker = JSF(
    default_interpolation_model_schema, allow_none_optionals=1
)


class DefaultInterpolationStub:
    """DefaultInterpolation unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return default_interpolation_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "DefaultInterpolation":
        """Create DefaultInterpolation stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DefaultInterpolationAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DefaultInterpolationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
