# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.delete_response import DeleteResponse

    DeleteResponseAdapter = TypeAdapter(DeleteResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

delete_response_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "messages" : {
      "title" : "Messages",
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/Message"
      }
    },
    "_links" : {
      "title" : " Links",
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/_Links"
      },
      "description" : "HAL links, indexed by link relation."
    },
    "_embeddings" : {
      "title" : " Embeddings",
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/_Embeddings"
      },
      "description" : "Hal embeddings, indexed by relation."
    }
  },
  "additionalProperties" : true,
  "description" : "Confirmation of a delete request."
}
""",
    object_hook=with_example_provider,
)
delete_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

delete_response_faker = JSF(delete_response_model_schema, allow_none_optionals=1)


class DeleteResponseStub:
    """DeleteResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return delete_response_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "DeleteResponse":
        """Create DeleteResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DeleteResponseAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DeleteResponseAdapter.validate_python(
            json, context={"skip_validation": True}
        )
