# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.embeddings import Embeddings

    EmbeddingsAdapter = TypeAdapter(Embeddings)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

embeddings_model_schema = json.loads(
    r"""{
  "title" : "_Embeddings",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/HALEmbedding"
  }, {
    "type" : "array",
    "items" : {
      "$ref" : "#/components/schemas/HALEmbedding"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
embeddings_model_schema.update({"definitions": MODEL_DEFINITIONS})

embeddings_faker = JSF(embeddings_model_schema, allow_none_optionals=1)


class EmbeddingsStub:
    """Embeddings unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return embeddings_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Embeddings":
        """Create Embeddings stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(EmbeddingsAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return EmbeddingsAdapter.validate_python(
            json, context={"skip_validation": True}
        )
