# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.grouping_interval_override_one_of import (
        GroupingIntervalOverrideOneOf,
    )

    GroupingIntervalOverrideOneOfAdapter = TypeAdapter(GroupingIntervalOverrideOneOf)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

grouping_interval_override_one_of_model_schema = json.loads(
    r"""{
  "type" : "string",
  "description" : "When `inferred` is specified, the frequency of aggregation will be inferred from the main/first time series. This can be used to regularize the time series",
  "enum" : [ "inferred" ]
}
""",
    object_hook=with_example_provider,
)
grouping_interval_override_one_of_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

grouping_interval_override_one_of_faker = JSF(
    grouping_interval_override_one_of_model_schema, allow_none_optionals=1
)


class GroupingIntervalOverrideOneOfStub:
    """GroupingIntervalOverrideOneOf unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return grouping_interval_override_one_of_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "GroupingIntervalOverrideOneOf":
        """Create GroupingIntervalOverrideOneOf stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                GroupingIntervalOverrideOneOfAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return GroupingIntervalOverrideOneOfAdapter.validate_python(
            json, context={"skip_validation": True}
        )
