# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.hierarchical import Hierarchical

    HierarchicalAdapter = TypeAdapter(Hierarchical)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hierarchical_model_schema = json.loads(
    r"""{
  "title" : "Hierarchical",
  "description" : "if true, use hierarchical objects to represent multiple row (or column) dimensions, otherwise multi-keys get concatenated with a dot-delimiter. If the value is a list, only these levels are kept as separate levels, while remaining levels get concatenated keys",
  "anyOf" : [ {
    "type" : "boolean"
  }, {
    "type" : "array",
    "items" : {
      "type" : "string"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
hierarchical_model_schema.update({"definitions": MODEL_DEFINITIONS})

hierarchical_faker = JSF(hierarchical_model_schema, allow_none_optionals=1)


class HierarchicalStub:
    """Hierarchical unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hierarchical_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Hierarchical":
        """Create Hierarchical stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                HierarchicalAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return HierarchicalAdapter.validate_python(
            json, context={"skip_validation": True}
        )
