# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.message_level import MessageLevel

    MessageLevelAdapter = TypeAdapter(MessageLevel)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

message_level_model_schema = json.loads(
    r"""{
  "title" : "Message_level",
  "type" : "string",
  "default" : "info",
  "enum" : [ "debug", "info", "warning", "error", "fatal" ]
}
""",
    object_hook=with_example_provider,
)
message_level_model_schema.update({"definitions": MODEL_DEFINITIONS})

message_level_faker = JSF(message_level_model_schema, allow_none_optionals=1)


class MessageLevelStub:
    """MessageLevel unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return message_level_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "MessageLevel":
        """Create MessageLevel stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MessageLevelAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MessageLevelAdapter.validate_python(
            json, context={"skip_validation": True}
        )
