# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.message_properties import MessageProperties

    MessagePropertiesAdapter = TypeAdapter(MessageProperties)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

message_properties_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "resource" : {
      "title" : "Series resource id",
      "type" : "string"
    },
    "metric" : {
      "title" : "Series metric",
      "type" : "string"
    }
  },
  "additionalProperties" : true,
  "description" : "Additional message arguments."
}
""",
    object_hook=with_example_provider,
)
message_properties_model_schema.update({"definitions": MODEL_DEFINITIONS})

message_properties_faker = JSF(message_properties_model_schema, allow_none_optionals=1)


class MessagePropertiesStub:
    """MessageProperties unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return message_properties_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "MessageProperties":
        """Create MessageProperties stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MessagePropertiesAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MessagePropertiesAdapter.validate_python(
            json, context={"skip_validation": True}
        )
