# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.query_list_item import QueryListItem

    QueryListItemAdapter = TypeAdapter(QueryListItem)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

query_list_item_model_schema = json.loads(
    r"""{
  "title" : "QueryListItem",
  "required" : [ "_links", "attrs", "name" ],
  "type" : "object",
  "properties" : {
    "_links" : {
      "$ref" : "#/components/schemas/QueryHALLinks"
    },
    "attrs" : {
      "title" : "Query attributes",
      "type" : "object",
      "description" : "System provided metadata for the query definition."
    },
    "name" : {
      "title" : "Query name",
      "type" : "string",
      "description" : "Name of the stored query definition."
    },
    "meta" : {
      "title" : "Query metadata",
      "type" : "object",
      "description" : "User metadata for the query definition."
    }
  },
  "additionalProperties" : true,
  "description" : "Listing of a query definition item."
}
""",
    object_hook=with_example_provider,
)
query_list_item_model_schema.update({"definitions": MODEL_DEFINITIONS})

query_list_item_faker = JSF(query_list_item_model_schema, allow_none_optionals=1)


class QueryListItemStub:
    """QueryListItem unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return query_list_item_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "QueryListItem":
        """Create QueryListItem stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                QueryListItemAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return QueryListItemAdapter.validate_python(
            json, context={"skip_validation": True}
        )
