# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.query_entity_input import QueryEntityInput

    QueryEntityInputAdapter = TypeAdapter(QueryEntityInput)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

query_entity_input_model_schema = json.loads(
    r"""{
  "required" : [ "name", "query" ],
  "type" : "object",
  "properties" : {
    "name" : {
      "title" : "Query name",
      "type" : "string",
      "description" : "Name of the stored query definition."
    },
    "meta" : {
      "title" : "Query metadata",
      "type" : "object",
      "description" : "User metadata for the query definition."
    },
    "query" : {
      "$ref" : "#/components/schemas/Query-Input"
    }
  },
  "additionalProperties" : true,
  "description" : "Input data to create a query definition."
}
""",
    object_hook=with_example_provider,
)
query_entity_input_model_schema.update({"definitions": MODEL_DEFINITIONS})

query_entity_input_faker = JSF(query_entity_input_model_schema, allow_none_optionals=1)


class QueryEntityInputStub:
    """QueryEntityInput unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return query_entity_input_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "QueryEntityInput":
        """Create QueryEntityInput stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                QueryEntityInputAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return QueryEntityInputAdapter.validate_python(
            json, context={"skip_validation": True}
        )
