# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.render_mode import RenderMode

    RenderModeAdapter = TypeAdapter(RenderMode)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

render_mode_model_schema = json.loads(
    r"""{
  "title" : "_RenderMode",
  "type" : "string",
  "description" : "Render mode configuration keys.",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/_RenderMode_oneOf"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_1"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_2"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_3"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_4"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_5"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_6"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_7"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_8"
  }, {
    "$ref" : "#/components/schemas/_RenderMode_oneOf_9"
  } ]
}
""",
    object_hook=with_example_provider,
)
render_mode_model_schema.update({"definitions": MODEL_DEFINITIONS})

render_mode_faker = JSF(render_mode_model_schema, allow_none_optionals=1)


class RenderModeStub:
    """RenderMode unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return render_mode_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "RenderMode":
        """Create RenderMode stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(RenderModeAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return RenderModeAdapter.validate_python(
            json, context={"skip_validation": True}
        )
