# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.render1_any_of import Render1AnyOf

    Render1AnyOfAdapter = TypeAdapter(Render1AnyOf)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

render_1_any_of_model_schema = json.loads(
    r"""{
  "$ref" : "#/components/schemas/_RenderMode"
}
""",
    object_hook=with_example_provider,
)
render_1_any_of_model_schema.update({"definitions": MODEL_DEFINITIONS})

render_1_any_of_faker = JSF(render_1_any_of_model_schema, allow_none_optionals=1)


class Render1AnyOfStub:
    """Render1AnyOf unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return render_1_any_of_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Render1AnyOf":
        """Create Render1AnyOf stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                Render1AnyOfAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return Render1AnyOfAdapter.validate_python(
            json, context={"skip_validation": True}
        )
