# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.row_headers_inner import RowHeadersInner

    RowHeadersInnerAdapter = TypeAdapter(RowHeadersInner)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

row_headers_inner_model_schema = json.loads(
    r"""{
  "title" : "Row_Headers_inner",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/ColumnIndexRowHeader"
  }, {
    "$ref" : "#/components/schemas/RowHeader"
  } ]
}
""",
    object_hook=with_example_provider,
)
row_headers_inner_model_schema.update({"definitions": MODEL_DEFINITIONS})

row_headers_inner_faker = JSF(row_headers_inner_model_schema, allow_none_optionals=1)


class RowHeadersInnerStub:
    """RowHeadersInner unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return row_headers_inner_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "RowHeadersInner":
        """Create RowHeadersInner stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                RowHeadersInnerAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return RowHeadersInnerAdapter.validate_python(
            json, context={"skip_validation": True}
        )
