# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.row_header import RowHeader

    RowHeaderAdapter = TypeAdapter(RowHeader)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

row_header_model_schema = json.loads(
    r"""{
  "required" : [ "timestamp" ],
  "type" : "object",
  "properties" : {
    "timestamp" : {
      "$ref" : "#/components/schemas/Timestamp"
    },
    "timestamp_iso" : {
      "$ref" : "#/components/schemas/TimestampIso"
    }
  },
  "additionalProperties" : true,
  "description" : "Index entry attributes.\n\nAttributes for a timestamp index entry."
}
""",
    object_hook=with_example_provider,
)
row_header_model_schema.update({"definitions": MODEL_DEFINITIONS})

row_header_faker = JSF(row_header_model_schema, allow_none_optionals=1)


class RowHeaderStub:
    """RowHeader unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return row_header_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "RowHeader":
        """Create RowHeader stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(RowHeaderAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return RowHeaderAdapter.validate_python(json, context={"skip_validation": True})
