# coding: utf-8
"""Waylay Query: timeseries queries (v1 protocol) model tests.

This code was generated from the OpenAPI documentation of 'Waylay Query: timeseries queries (v1 protocol)'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.queries.models.row_data_set_data_axis import RowDataSetDataAxis

    RowDataSetDataAxisAdapter = TypeAdapter(RowDataSetDataAxis)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

row_data_set_data_axis_model_schema = json.loads(
    r"""{
  "title" : "RowDataSet_data_axis",
  "type" : "string",
  "default" : "column",
  "enum" : [ "column" ]
}
""",
    object_hook=with_example_provider,
)
row_data_set_data_axis_model_schema.update({"definitions": MODEL_DEFINITIONS})

row_data_set_data_axis_faker = JSF(
    row_data_set_data_axis_model_schema, allow_none_optionals=1
)


class RowDataSetDataAxisStub:
    """RowDataSetDataAxis unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return row_data_set_data_axis_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "RowDataSetDataAxis":
        """Create RowDataSetDataAxis stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                RowDataSetDataAxisAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return RowDataSetDataAxisAdapter.validate_python(
            json, context={"skip_validation": True}
        )
